### get info about bot
GET {{ host }}/me
Authorization: {{token}}

### change bot info
PATCH {{ host }}/me
Authorization: {{token}}
Content-Type: application/json

{
  "first_name": "cutie bot",
  "description": "your cutie bot",
  "commands": [
    {
      "name": "/help",
      "description": "Commands and any info"
    }
  ]
}
